vlibras-video-portal/config/routes.rb
# -*- encoding : utf-8 -*-
Rails.application.routes.draw do
  devise_for :users

  constraints CanAccessDelayedJobWeb do
    namespace :admin do
      match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
    end
  end

  ActiveAdmin.routes(self)

  root 'static#home', as: :home

  namespace :v_libras do
    resources :requests, :only => [ :new, :create ] do
      get 'rapid', on: :collection
      post 'callback', on: :collection
    end

    resources :videos, :only => [ :index, :show, :destroy ]


  end

end

vlibras-video-portal/app/models/v_libras.rb
# -*- encoding : utf-8 -*-
module VLibras
  def self.table_name_prefix
    'v_libras_'
  end
end

vlibras-video-portal/app/models/v_libras/request.rb
# -*- encoding : utf-8 -*-
# == Schema Information
#
# Table name: v_libras_requests
#
#  id             :integer          not null, primary key
#  status         :string(255)
#  service_type   :string(255)
#  owner_id       :integer
#  params         :text
#  response       :text
#  created_at     :datetime
#  updated_at     :datetime
#  video_filename :string(255)
#

class VLibras::Request < ActiveRecord::Base
  serialize :params
  attr_accessor :files

  belongs_to :owner, :class => User

  has_one :video, :class => VLibras::Video, :dependent => :destroy

  validates :service_type,
            presence: true,
            inclusion: { in: %w(video-legenda video) }

  validates :status,
            presence: true,
            inclusion: { in: %w(created processing error success) }

  validate :match_files_with_service_type

  before_validation :default_values

  default_scope { order('created_at DESC') }

  def self.build_from_params(params, user)
    request = self.new

    request.service_type = params[:service]
    request.owner = user

    request.files = {}

    if params[:video]
      request.video_filename = params[:video].original_filename
      video = FileUploader.new
      video.cache!(params[:video])
      request.files.merge!(:video => video)
    end

    if params[:subtitle]
      subtitle = FileUploader.new
      subtitle.cache!(params[:subtitle])
      request.files.merge!(:subtitle => subtitle)
    end

    request.params = params[:params]

    request
  end

  def perform_request(files)
    logger.debug '[VLibras::Request] Starting request'
    self.update!(status: 'processing')

    ApiClient::Client.submit(self, files)

    # Warning: this code is also present on the controller, if there is an error
    files.values.each { |f| f.file.delete }

    logger.debug '[VLibras::Request] Request done'
  end

private
  def match_files_with_service_type
    return unless files

    if files[:video].nil?
      errors.add(:base, 'Você precisa enviar um vídeo.')
    end

    if (service_type == 'video-legenda') && files[:subtitle].nil?
      errors.add(:base, 'Você precisa enviar uma legenda.')
    end
  end

  def default_values
    self.status ||= 'created'
  end
end

vlibras-video-portal/app/models/v_libras/video.rb
# -*- encoding : utf-8 -*-
# == Schema Information
#
# Table name: v_libras_videos
#
#  id         :integer          not null, primary key
#  request_id :integer
#  url        :string(255)
#  created_at :datetime
#  updated_at :datetime
#  seen       :boolean
#

class VLibras::Video < ActiveRecord::Base
  belongs_to :request, :class => VLibras::Request, :dependent => :delete

  validates :request_id, :url, :presence => true

  before_validation :default_values

  scope :not_seen, -> { where(:seen => false) }

  def mark_as_seen!
    self.update!(:seen => true) unless self.seen
  end

  def thumb
    self.url.gsub('flv', 'png')
  end

  def url_mp4
    self.url.gsub('flv', 'mp4')
  end

protected
  def default_values
    self.seen = false if self.seen.nil?

    return true
  end
end

vlibras-video-portal/app/controllers/v_libras/requests_controller.rb
# -*- encoding : utf-8 -*-
class VLibras::RequestsController < ApplicationController
  protect_from_forgery with: :null_session, :only => [ :callback ]

  before_filter :authenticate_user!, :except => [ :callback ]
  before_filter :check_vlibras_api_status, :except => [ :callback ]

  def rapid
    @request = VLibras::Request.new
  end

  def new

  end

  def create
    @request = VLibras::Request.build_from_params(params, current_user)

    if @request.save
      @request.perform_request(@request.files)
      p 'rerouitsme1'

      flash[:success] = 'Sua requisição foi submetida com sucesso!'

      render json: { status: 'ok', redirect_to: v_libras_videos_path('video-wait' => true)}, status: 200
    else
      flash[:error] = 'Algo deu errado com a sua requisição. Por favor verifique opções escolhidas.'
      flash[:warning] = @request.errors.full_messages.to_sentence.humanize

      # Warning: this code is also present on #perform_request, if the request is successfully done
      @request.files.values.each { |f| f.file.delete }

      # same as redirect :back
      render json: { status: 'error', redirect_to: request.headers["Referer"]}, status: 400
    end
  end

  def callback
    ApiClient::CallbackProcessor.process(params)

    render :text => "OK!"
  end
end

vlibras-video-portal/app/controllers/v_libras/videos_controller.rb
# -*- encoding : utf-8 -*-
class VLibras::VideosController < InheritedResources::Base
  actions :show, :destroy

  before_filter :check_vlibras_api_status, :only => [ :index, :show ]
  before_filter :authenticate_user!

  before_filter :mark_as_seen!, :only => [ :show ]

  def index
    @videos = current_user.videos.page(params[:page]).per(9)
    @requests = current_user.requests.limit(6)
  end

protected
  def mark_as_seen!
    @video = VLibras::Video.find(params[:id])
    @video.mark_as_seen!
  end
end

vlibras-video-portal/app/helpers/v_libras/videos_helper.rb
# -*- encoding : utf-8 -*-
module VLibras::VideosHelper
end

vlibras-video-portal/app/views/v_libras/videos/index.haml
#encoding: UTF-8

= include_videojs_assets

- content_for :js do
  = javascript_include_tag "v_libras/videos/index"

.breadcrumb
  %h3= t('videos.list')

.well
  - @videos.in_groups_of(3, false) do |group|
    .row-fluid.text-center.videos-row
      - for video in group
        .span4
          .ribbon-wrapper-green
            .ribbon-content
              = link_to html5_video_tag(video.url_mp4, 'video-vlibras', '', '{ "controls": false, "autoplay": true }'), video
            - unless video.seen
              .ribbon-green Novo

          %div
            %span
              = link_to video.url_mp4, class: "btn btn-success" do
                = content_tag(:span, '', :class => 'icon-download icon-white')
                Baixar

            %span
              = link_to content_tag(:span, '', :class => 'icon-trash icon-white'),  v_libras_video_path(video), method: :delete,
                class: "btn btn-danger", data: { confirm: t('shared.confirm_delete') }


  .row-fluid.text-center.pagination
    .row12
      = paginate @videos


- if @requests.any?
  .breadcrumb.requests
    %h4= t('requests.list')

  .well
    .row-fluid
      .span8.offset2
        %table.table.table-hover.table-striped.table-requests
          %thead
            %tr
              %th Situação
              %th Vídeo
              %th Criado há

          - @requests.each do |request|
            %tr
              %td.span2= request_status_label(request)
              %td.span5= request.video_filename
              %td.span5= time_ago_in_words(request.created_at)


- if params['video-wait']
  #modal-wait.modal.fade
    .modal-header
      %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
      %h3 Aguarde...
    .modal-body
      = html5_video_tag(['/system/videos/aguarde.mp4'], 'video-wait', 'video-instructions auto-margin',
        '{ "preload": true, "controls": false, "autoplay": true, "loop": true }')

    .modal-footer
      %a.btn{"aria-hidden" => "true", "data-dismiss" => "modal", href: "#"} Fechar

  - content_for :javascript_code do
    :javascript
      current_user = #{current_user.id};

      $(function () {
        $('#modal-wait').modal();
      })

vlibras-video-portal/app/views/v_libras/videos/show.haml
= include_videojs_assets

.breadcrumb
  %h3= "Vídeo #{@video.request.video_filename}"

.row-fluid
  .span12.well
    .video-vlibras.text-center
      = html5_video_tag(@video.url_mp4,
                  'video-vlibras', '', '{ "controls": true, "autoplay": false }')