vlibras-video-portal/config/routes.rb
# -*- encoding : utf-8 -*-
Rails.application.routes.draw do
  devise_for :users

  constraints CanAccessDelayedJobWeb do
    namespace :admin do
      match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
    end
  end

  ActiveAdmin.routes(self)

  root 'static#home', as: :home

  namespace :v_libras do
    resources :requests, :only => [ :new, :create ] do
      get 'rapid', on: :collection
      post 'callback', on: :collection
    end

    resources :videos, :only => [ :index, :show, :destroy ]


  end

end

vlibras-video-portal/app/views/layouts/_menu.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container-fluid
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        .icon-bar
        .icon-bar
        .icon-bar


      = link_to "VLibras-Vídeo", home_path, :class => "brand"

      .nav-collapse
        %ul.nav
          - if current_user.present?

            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                = t('shared.vlibras')
                - if current_user.videos.not_seen.any?
                  %span.label.label-success Novo vídeo!
                %strong.caret
              %ul.dropdown-menu
                %li
                  = link_to v_libras_videos_path do
                    = t('wikivideos.my_videos')
                    - if current_user.videos.not_seen.any?
                      %span.label.label-success= current_user.videos.not_seen.size
                %li= link_to t('videos.new'), new_v_libras_request_path
                %li.divider
                %li= link_to t('shared.form_alternative'), rapid_v_libras_requests_path

            %li.dropdown.hidden
              %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                = t('shared.wikilibras')
                %strong.caret
              %ul.dropdown-menu
                %li= link_to t('wikivideos.my_signals'), '#'
                %li= link_to t('wikivideos.cadastro_sinal'), '#'
                %li.divider
                %li= link_to t('wikivideos.dicionario_de_dados'), '#'

            %li.hidden= link_to t('shared.slibras')

          %li= link_to t('shared.about'), "http://www.vlibras.com.br", :target => "blank"

        - if current_user.present?
          .nav-collapse.pull-right.user-menu
            %ul.nav
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                  = current_user.name
                  %strong.caret
                %ul.dropdown-menu
                  %li= link_to t('shared.logout'), destroy_user_session_path, :method => 'delete'

          /
            <ul class="nav secondary-nav">
            <li><haml_loud> link_to image_tag('pt.png'), url_for( :locale => 'pt' ), :title => "Português" </haml_loud></li>
            <li><haml_loud> link_to image_tag('en.png'), url_for( :locale => 'en' ), :title => 'English' </haml_loud></li>
            </ul>

vlibras-video-portal/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VLibras-Vídeo</title>
  <%= javascript_include_tag "application" %>
  <%= yield :js %>

  <%= yield :javascript_code %>

  <%= yield :css %>
  <%= stylesheet_link_tag  "application", :media => "all" %>

  <%= yield :css_code %>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <script type="text/javascript">
      document.createElement('video');document.createElement('audio');document.createElement('track');
  </script>
</head>

<body>
<%= render 'layouts/menu' %>

<div class="container-fluid">
  <% if content_for?(:menu) %>
  <div class="breadcrumb">
    <%= yield :menu %>
  </div>
  <% end %>

    <% flash.each do |type, message| %>
      <div class="alert <%= bootstrap_class_for(type) %> fade in">
        <button class="close" data-dismiss="alert">×</button>
        <%= message %>
      </div>
    <% end %>

    <%= yield %>

  <footer>
    <p>VLibras-Vídeo - <%= t('shared.project') %>
      <a href="http://www.vlibras.com.br" target="_blank">LAVID</a> |
      &copy; <%= Time.now.year %>. <%= t('shared.copyright') %>.</p>
  </footer>
</div>


<%= yield :bottom %>

</body>
</html>