vlibras-video-portal/config/routes.rb
# -*- encoding : utf-8 -*-
Rails.application.routes.draw do
  devise_for :users

  constraints CanAccessDelayedJobWeb do
    namespace :admin do
      match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
    end
  end

  ActiveAdmin.routes(self)

  root 'static#home', as: :home

  namespace :v_libras do
    resources :requests, :only => [ :new, :create ] do
      get 'rapid', on: :collection
      post 'callback', on: :collection
    end

    resources :videos, :only => [ :index, :show, :destroy ]


  end

end

vlibras-video-portal/app/models/v_libras.rb
# -*- encoding : utf-8 -*-
module VLibras
  def self.table_name_prefix
    'v_libras_'
  end
end

vlibras-video-portal/app/models/v_libras/request.rb
# -*- encoding : utf-8 -*-
# == Schema Information
#
# Table name: v_libras_requests
#
#  id             :integer          not null, primary key
#  status         :string(255)
#  service_type   :string(255)
#  owner_id       :integer
#  params         :text
#  response       :text
#  created_at     :datetime
#  updated_at     :datetime
#  video_filename :string(255)
#

class VLibras::Request < ActiveRecord::Base
  serialize :params
  attr_accessor :files

  belongs_to :owner, :class => User

  has_one :video, :class => VLibras::Video, :dependent => :destroy

  validates :service_type,
            presence: true,
            inclusion: { in: %w(video-legenda video) }

  validates :status,
            presence: true,
            inclusion: { in: %w(created processing error success) }

  validate :match_files_with_service_type

  before_validation :default_values

  default_scope { order('created_at DESC') }

  def self.build_from_params(params, user)
    request = self.new

    request.service_type = params[:service]
    request.owner = user

    request.files = {}

    if params[:video]
      request.video_filename = params[:video].original_filename
      video = FileUploader.new
      video.cache!(params[:video])
      request.files.merge!(:video => video)
    end

    if params[:subtitle]
      subtitle = FileUploader.new
      subtitle.cache!(params[:subtitle])
      request.files.merge!(:subtitle => subtitle)
    end

    request.params = params[:params]

    request
  end

  def perform_request(files)
    logger.debug '[VLibras::Request] Starting request'
    self.update!(status: 'processing')

    ApiClient::Client.submit(self, files)

    # Warning: this code is also present on the controller, if there is an error
    files.values.each { |f| f.file.delete }

    logger.debug '[VLibras::Request] Request done'
  end

private
  def match_files_with_service_type
    return unless files

    if files[:video].nil?
      errors.add(:base, 'Você precisa enviar um vídeo.')
    end

    if (service_type == 'video-legenda') && files[:subtitle].nil?
      errors.add(:base, 'Você precisa enviar uma legenda.')
    end
  end

  def default_values
    self.status ||= 'created'
  end
end

vlibras-video-portal/app/models/v_libras/video.rb
# -*- encoding : utf-8 -*-
# == Schema Information
#
# Table name: v_libras_videos
#
#  id         :integer          not null, primary key
#  request_id :integer
#  url        :string(255)
#  created_at :datetime
#  updated_at :datetime
#  seen       :boolean
#

class VLibras::Video < ActiveRecord::Base
  belongs_to :request, :class => VLibras::Request, :dependent => :delete

  validates :request_id, :url, :presence => true

  before_validation :default_values

  scope :not_seen, -> { where(:seen => false) }

  def mark_as_seen!
    self.update!(:seen => true) unless self.seen
  end

  def thumb
    self.url.gsub('flv', 'png')
  end

  def url_mp4
    self.url.gsub('flv', 'mp4')
  end

protected
  def default_values
    self.seen = false if self.seen.nil?

    return true
  end
end

vlibras-video-portal/app/controllers/v_libras/requests_controller.rb
# -*- encoding : utf-8 -*-
class VLibras::RequestsController < ApplicationController
  protect_from_forgery with: :null_session, :only => [ :callback ]

  before_filter :authenticate_user!, :except => [ :callback ]
  before_filter :check_vlibras_api_status, :except => [ :callback ]

  def rapid
    @request = VLibras::Request.new
  end

  def new

  end

  def create
    @request = VLibras::Request.build_from_params(params, current_user)

    if @request.save
      @request.perform_request(@request.files)
      p 'rerouitsme1'

      flash[:success] = 'Sua requisição foi submetida com sucesso!'

      render json: { status: 'ok', redirect_to: v_libras_videos_path('video-wait' => true)}, status: 200
    else
      flash[:error] = 'Algo deu errado com a sua requisição. Por favor verifique opções escolhidas.'
      flash[:warning] = @request.errors.full_messages.to_sentence.humanize

      # Warning: this code is also present on #perform_request, if the request is successfully done
      @request.files.values.each { |f| f.file.delete }

      # same as redirect :back
      render json: { status: 'error', redirect_to: request.headers["Referer"]}, status: 400
    end
  end

  def callback
    ApiClient::CallbackProcessor.process(params)

    render :text => "OK!"
  end
end

vlibras-video-portal/app/controllers/v_libras/videos_controller.rb
# -*- encoding : utf-8 -*-
class VLibras::VideosController < InheritedResources::Base
  actions :show, :destroy

  before_filter :check_vlibras_api_status, :only => [ :index, :show ]
  before_filter :authenticate_user!

  before_filter :mark_as_seen!, :only => [ :show ]

  def index
    @videos = current_user.videos.page(params[:page]).per(9)
    @requests = current_user.requests.limit(6)
  end

protected
  def mark_as_seen!
    @video = VLibras::Video.find(params[:id])
    @video.mark_as_seen!
  end
end

vlibras-video-portal/app/helpers/v_libras/videos_helper.rb
# -*- encoding : utf-8 -*-
module VLibras::VideosHelper
end

vlibras-video-portal/app/views/v_libras/requests/_position_step.haml
#position-step.wrapper
  .video_wrapper

  = html5_video_tag(['/system/videos/workflow/localizacao.mp4'],
        'id-4', 'video-wizard', '{ "preload": "none", "controls": false }')

- content_for :javascript_code do
  :javascript
    $(function () {
      var optionsPosition = {
          video: { width: 940, height: 530 },
          buttons: [ { id: 'btn-red-light3', path: '/system/images/video/red-button.png', clickable: false, start: 0.1, end: 19.1, x: 440, y: 516, delay: 300, value: null },
                     { id: 'btn-green-light3', path: '/system/images/video/green-button.png', clickable: false, start: 14.9, end: 999, x: 440, y: 512, delay: 300, value: null },
                     { id: 'b_loc_1', path: '/system/images/loc/p_1.png', clickable: false, start: 9, end: 9.5, x: 500, y: 350, delay: 300, value: null },
                     { id: 'b_loc_2', path: '/system/images/loc/p_2.png', clickable: false, start: 11, end: 11.5, x: 330, y: 340, delay: 300, value: null },
                     { id: 'b_loc_3', path: '/system/images/loc/p_3.png', clickable: false, start: 12.8, end: 13.3, x: 300, y: 40, delay: 300, value: null },
                     { id: 'b_loc_4', path: '/system/images/loc/p_4.png', clickable: false, start: 14.5, end: 15, x: 530, y: 40, delay: 300, value: null },
                     { id: 'b_loc_5', path: '/system/images/loc/p_4.png', clickable: true, start: debugTime(15), end: 9999, x: 150, y: 30, delay: 300, value: "top_left" },
                     { id: 'b_loc_6', path: '/system/images/loc/p_3.png', clickable: true, start: debugTime(15), end: 9999, x: 680, y: 30, delay: 300, value: "top_right" },
                     { id: 'b_loc_7', path: '/system/images/loc/p_1.png', clickable: true, start: debugTime(15), end: 9999, x: 680, y: 410, delay: 300, value: "bottom_left" },
                     { id: 'b_loc_8', path: '/system/images/loc/p_2.png', clickable: true, start: debugTime(15), end: 9999, x: 150, y: 410, delay: 300, value: "bottom_right" }
          ]
      };

      var VLibrasPosition = new VLibrasLocalization();
      console.log("POSICAO");
      VLibrasPosition.init("#position-step", optionsPosition);
    });

vlibras-video-portal/app/views/v_libras/requests/_service_step.haml
#service-step.wrapper
  .video_wrapper

  = html5_video_tag(['/system/videos/workflow/sub_audio.mp4'],
      'id-2', 'video-wizard', '{ "preload": "none", "controls": false }')

  .row-fluid.hide
    .span1.offset3
      = label_tag :video, t('videos.subtitle'), :class => "bold"

    .span5
      = file_field_tag 'subtitle', :id => 'subtitle-upload',
        :accept => '.srt'


- content_for :javascript_code do
  :javascript
    $(function () {
      var optionsService = {
          video: { width: 940, height: 530 },
          buttons: [ { id: 'btn-red-light2', path: '/system/images/video/red-button.png', clickable: false, start: 0.1, end: 8, x: 440, y: 516, delay: 300, value: null },
                     { id: 'btn-green-light2', path: '/system/images/video/green-button.png', clickable: false, start: 8, end: 999, x: 440, y: 512, delay: 300, value: null },
                     { id: 'btn-video-legenda', path: '/system/images/sub_audio/p_1.png', clickable: true, start: debugTime(8), end: 9999, x: 415, y: 417, delay: 300 },
          ]
      };

      var VLibrasSubAudio = new VLibrasLocalization();
      VLibrasSubAudio.init("#service-step", optionsService);
    });

vlibras-video-portal/app/views/v_libras/requests/_size_step.haml
#size-step.wrapper
  .video_wrapper

  = html5_video_tag(['/system/videos/workflow/tamanho.mp4'],
        'id-3', 'video-wizard', '{ "preload": "none", "controls": false }')


- content_for :javascript_code do
  :javascript
    $(function () {
      var optionsSize = {
          video: { width: 940, height: 530 },
          buttons: [ { id: 'btn-red-light4', path: '/system/images/video/red-button.png', clickable: false, start: 0.1, end: 5, x: 440, y: 516, delay: 300, value: null },
                     { id: 'btn-green-light4', path: '/system/images/video/green-button.png', clickable: false, start: 5, end: 999, x: 440, y: 512, delay: 300, value: null },
                     { id: 'b1_size_small', path: '/system/images/size/p_1.png', clickable: false, start: 3.8, end: 5, x: 603, y: 379, delay: 300, value: null },
                     { id: 'b1_size_med', path: '/system/images/size/p_2.png', clickable: false, start: 4.2, end: 5, x: 543, y: 339, delay: 300, value: null },
                     { id: 'b1_size_big', path: '/system/images/size/p_3.png', clickable: false, start: 4.6, end: 5, x: 473, y: 293, delay: 300, value: null},
                     { id: 'b2_size_small', path: '/system/images/size/p_1.png', clickable: true, start: debugTime(5), end: 9999, x: 603, y: 379, delay: 300, value: "small" },
                     { id: 'b2_size_med', path: '/system/images/size/p_2.png', clickable: true, start: debugTime(5), end: 9999, x: 543, y: 339, delay: 300, value: "medium" },
                     { id: 'b2_size_big', path: '/system/images/size/p_3.png', clickable: true, start: debugTime(5), end: 9999, x: 473, y: 293, delay: 300, value: "large" }
          ]
      };

      var VLibrasSize = new VLibrasLocalization();
      VLibrasSize.init("#size-step", optionsSize);
    });

vlibras-video-portal/app/views/v_libras/requests/_video_step.haml
#video-step.wrapper
  .video_wrapper

  = html5_video_tag(['/system/videos/workflow/video.mp4'],
    'video-video', 'video-wizard', '{ "autoplay": true, "controls": false } ')

  .row-fluid.hide
    .span1.offset3
      = label_tag :video, t('videos.url'), :class => "bold"

    .span5
      = file_field_tag 'video', :id => 'video-upload',
        :accept => '.flv, .ts, .avi, .mp4, .mov, .webm, .wmv, .mkv'

.hide
  = image_tag '/system/images/video/red-button.png'
  = image_tag '/system/images/video/green-button.png'

- content_for :javascript_code do
  :javascript
    $(function () {
      var optionsVideo = {
          video: { width: 940, height: 530 },
          buttons: [ { id: 'btn-red-light1', path: '/system/images/video/red-button.png', clickable: false, start: 0.1, end: 17, x: 440, y: 516, delay: 100, value: null },
                     { id: 'btn-green-light1', path: '/system/images/video/green-button.png', clickable: false, start: 17, end: 999, x: 440, y: 512, delay: 100, value: null },
                     { id: 'btn-video-upload', path: '/system/images/video/p_1.png', clickable: true, start: debugTime(17), end: 9999, x: 415, y: 410, delay: 100 }
          ]
      };

      var VLibrasVideo = new VLibrasLocalization();
      VLibrasVideo.init("#video-step", optionsVideo);
    });

vlibras-video-portal/app/views/v_libras/requests/new.haml
:javascript
  $(function() {
    $.contra( function() {
      alert('Bem vindo ao modo debug! Os botões irão aparecer na tela antes do tempo normal.');
      window.location.href = window.location.href + "?debug";
    }, { code : [ 68, 69, 66, 85, 71 ] } );
  });

= include_videojs_assets

- content_for :js do
  = javascript_include_tag "jquery.steps.js"
  = javascript_include_tag "jquery.contra.min.js"
  = javascript_include_tag "v_libras/requests/shared"
  = javascript_include_tag "v_libras/requests/new"
  = javascript_include_tag "v_libras/requests/workflow"

- content_for :css do
  = stylesheet_link_tag "jquery.steps.css"
  = stylesheet_link_tag "v_libras/requests"

.breadcrumb
  %h3 Novo vídeo

= form_tag v_libras_requests_path, method: :post, :multipart => true, :id => 'vlibras-form' do |f|
  .content.row-fluid
    #vlibras-wizard

      %h2 Vídeo
      %section
        = render :partial => 'video_step'

      %h2 Legenda
      %section
        = render :partial => 'service_step'

      %h2 Posição
      %section
        = render :partial => 'position_step'

      %h2 Tamanho
      %section
        = render :partial => 'size_step'

    #menu.center.hide
      = button_tag 'Próximo', :class => "btn btn-large btn-success", :id => 'btn-next', :disabled => true

    .progress.progress-striped.active.hide{:style => 'position: relative;'}
      #upload-bar.bar
      #upload-label.center{:style => 'position: absolute; width: 100%; font-size: 12px;'}

.row-fluid
  #step-service

  #step-video-upload

  #step-subtitle-upload

  #step-size

  #step-position

vlibras-video-portal/app/views/v_libras/requests/rapid.haml
- content_for :js do
  = javascript_include_tag "v_libras/requests/shared"
  = javascript_include_tag "v_libras/requests/rapid"

#vlibras-rapid.row-fluid
  .span4.offset4.login
    %h2
      = t('videos.new')

    = form_tag v_libras_requests_path, method: :post, :multipart => true, :id => 'vlibras-rapid-form' do |f|
      - if @request.errors.any?
        #error_explanation
          %p/
          %h4
            = pluralize(@request.errors.count, "erro")
            impede o vídeo de ser salvo:
          %ul
            - @request.errors.full_messages.each do |msg|
              %li.error= msg

      .field.hide
        = label_tag :service, t('videos.video_type'), :class => 'bold'

        %label.radio
          = radio_button_tag :service, 'video-legenda', true, :id => 'service-video-subtitle'
          Vídeo e legenda (.srt)

      #url.field
        = label_tag :video, t('videos.url'), :class => "bold"

        %span.btn.fileinput-button
          %i.icon-film
          %span.button-text Escolha o vídeo...
          = file_field_tag :video, :prompt => "Arquivo de vídeo", :id => 'video-upload',
            :accept => '.flv, .ts, .avi, .mp4, .mov, .webm, .wmv, .mkv'

      #legend.field
        = label_tag :subtitle, t('videos.subtitle'), :class => "bold"

        %span.btn.fileinput-button
          %i.icon-list-alt
          %span.button-text Escolha a legenda...
          = file_field_tag :subtitle, :prompt => "Arquivo de legenda", :id => 'subtitle-upload',
            :accept => '.srt'

      .field
        = label_tag 'params[tamanho]', t('videos.window_size'), :class => "bold"
        = select_tag 'params[tamanho]', options_for_select([['Pequena', 'small'], ['Média', 'medium'], ['Grande', 'large']])

      .field
        %p
          %b
            = label_tag 'params[posicao]',  t('videos.window_position'), :class => "bold"
            = select_tag 'params[posicao]', options_for_select([[t('videos.top_left'),
              'top_left'], [t('videos.top_right'), 'top_right'],
              [t('videos.bottom_right'),'bottom_right'], [t('videos.bottom_left'), 'bottom_left']])

      .field.hide
        = label_tag 'params[transparencia]', t('videos.transparency'), :class => "bold"
        = select_tag 'params[transparencia]', options_for_select([['Opaco', 'opaco'], ['Transparente', 'transparente']])

      .progress.progress-striped.active.hide{:style => 'position: relative;'}
        #upload-bar.bar
        #upload-label.center{:style => 'position: absolute; width: 100%; font-size: 12px;'}

      = button_tag "Confirmar", :class => "btn btn-success btn-large actions", :id => 'submit-button'